# Step 1: Use an official Node.js base image
FROM node:lts-alpine

# Step 2: Set working directory in the container
WORKDIR /backend-apps

# Step 3: Copy package.json and package-lock.json first (for better caching)
COPY package*.json ./

# Step 4: Install dependencies
RUN npm install

# Step 5: Copy the rest of your application code
COPY . .

RUN npx prisma generate

# Step 6: Expose the port your app runs on //ส่งออก port ข้างนอกให้เข้าถึง
EXPOSE 8000

# Step 7: Start the app
# CMD ["npm", "run", "dev", "--", "--host","--port","3000" ] // set ให้ port vite server ใน container เป็น 3000 
CMD ["npm", "start"]


